Repository floneum/floneum, pull requests merged in 2025-04, with the labels that each got.

#371 fix CI
  .github/workflows/macos.yml
  .github/workflows/main.yml
  .github/workflows/windows.yml
Labels: bug, ci

#369 Bump ort to 2.0 RC 9
  Cargo.lock
  interfaces/kalosm-sound/Cargo.toml
Labels: dependencies, Kalosm

#370 Upgrade readability to 0.3.0
  Cargo.lock
  interfaces/kalosm-language/Cargo.toml
Labels: dependencies

#374 Make the cache used for WuerstchenBuilder configurable
  models/rwuerstchen/src/lib.rs
Labels: enhancement, Kalosm, image

#376 Fix whisper timestamp panic
  Cargo.lock
  interfaces/kalosm-common/src/kv_cache.rs
  models/rwhisper/Cargo.toml
  models/rwhisper/examples/transcribe_file.rs
  models/rwhisper/src/model.rs
  models/rwhisper/src/quantized/mod.rs
  models/rwhisper/src/quantized/timestamps.rs
  models/rwhisper/tests/odyssey.rs
Labels: bug, Kalosm, sound
